all:
  hosts:
    production:
      ansible_host: "192.168.31.62"
      ansible_user: "root"
      ansible_port: 22
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  vars:
    app_name: kizoxy
    app_dir: /opt/kizoxy
    app_repo: "https://github.com/kenewjr/Kizoxy.git"
    app_branch: main
    node_version: "20"
